Thip/enhancement 1 server client
wyncode/C40_Final_Eimy_Keith_Sebastian_Thip pull request #2
Opened 2020-12-17 03:31 UTC by thipkeovilay

Closes #1.

2020-12-17 13:49 UTC, leopolicastro requested changes
Show me this running on your computer and I'll approve it.

2020-12-17 13:49 UTC, leopolicastro commented on server/db/models/community.js
> +      default: false
Is this right?  Area is a boolean?

2020-12-17 22:08 UTC, xsebastianx approved these changes

2020-12-17 22:09 UTC, Amyeimy approved these changes

2020-12-18 22:09 UTC, Amyeimy approved these changes

2020-12-18 22:23 UTC, leopolicastro approved these changes

2020-12-18 22:23 UTC, merged